---
title: "412 Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Data
```{r wrap-hook}
library(readr)
library(dplyr)
library(ggplot2)
library(DataExplorer)
library(lubridate)
library(caTools)
library(MASS)
library(leaps)
library(caret)
library(pcr)
library(pls)
library(Metrics)
set.seed(1)
library(dplyr)
library(data.table)
house <- read.csv('house.csv')
head(house)
dim(house)
```

### Basic EDA
```{r}
IQR <- 645000-321950
Upper <- 1.5*IQR + 540088
Lower <- 540088 - 1.5*IQR
house <- subset(house, price >= Lower & price <= Upper)
summary(house)
# Add a feature if there is a basement then 1 else 0
for(i in 1: nrow(house)){
    if (house$sqft_basement[i] >0) {
  house$sqft_basement_yesno[i] <- 1
  } else {
  house$sqft_basement_yesno[i] <- 0
  }
}

IQR <- 645000-321950
Upper <- 1.5*IQR + 540088
Lower <- 540088 - 1.5*IQR
house <- subset(house, price >= Lower & price <= Upper)
drop <- c('date','id','zipcode','sqft_basement')
house <- house[!names(house) %in% drop]
summary(house)
dim(house)

```


```{r}
library(randomForest)
house.rf <- randomForest(price ~ ., data = house,
                         importance = TRUE)
print(house.rf)
import <- house.rf$importance
import
```

```{r}
keep <- c('price','lat','sqft_living','grade','sqft_living15','sqft_above','long','yr_built','sqft_lot15','sqft_lot','bathrooms')
house <- house[names(house) %in% keep]
summary(house)
```

```{r}
# house$bathrooms = as.factor(house$bathrooms)
# house$grade = as.factor(house$grade)
```

```{r}
s = sort(sample(nrow(house), nrow(house)*.7))
train <- house[s,]
test <- house[-s,]
```

### Models
```{r}
rmse <- function(y_hat, y) sqrt(mean((y_hat - y)^2))
lmodel <- lm(price~., data=train)
summary(lmodel)
rmse(test$price, predict(lmodel,test[-1]))
lmstep <- step(lmodel)
summary(lmstep)
rmse(test$price, predict(lmstep,test[-1]))
```

```{r}
library(leaps)
library(caTools)
pcdata <- prcomp(train[-1], scale = TRUE)
summary(pcdata)
```

```{r}
lm2 <- lm(train$price ~ pcdata$x[,1:8])
summary(lm2)
rmse(test$price, predict(lm2, test[-1]))
```

```{r}
library(randomForest)
house.rf <- randomForest(price ~ ., data = train,
                         importance = TRUE)
print(house.rf)
rmse(test$price, predict(house.rf, test[-1]))
house.rf$importance
```
